apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
  labels:
    app: blueplayer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: blueplayer
  template:
    metadata:
      labels:
        app: blueplayer
    spec:
      containers:
      - name: blueplayer1
        image: blueplayer.azurecr.io/blue-player
        ports:
        - containerPort: 5000
        env:
          - name: AZURE_STORAGE_KEY
            valueFrom:
              secretKeyRef:
                name: azure-secret
                key: storage-key
          - name: FLASK_SECRET
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: flask-key
