apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
  labels:
    app: blueplayer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: blueplayer
  template:
    metadata:
      labels:
        app: blueplayer
    spec:
      containers:
      - name: blueplayer1
        image: blueplayer.azurecr.io/blue-player
        ports:
        - containerPort: 5000
        env:
          - name: "PASSWORD"
            value: testpass123!@#
          - name: "DB"
            value: testdb
          - name: "HOST"
            value: 104.198.62.251
          - name: "USER"
            value: root
